name: Deploy al server tramite VPN
on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Installazione WireGuard
        run: sudo apt update && sudo apt install -y wireguard

      - name: Set up di WireGuard
        run: |
          echo "[Interface]
          PrivateKey = ${{ secrets.WG_PRIVATE_KEY }}
          Address = 10.60.223.3/24
          MTU = 1420

          [Peer]
          PublicKey = ${{ secrets.WG_SERVER_PUBLIC_KEY }}
          Endpoint = ${{ secrets.SSH_PUBLIC_IP }}:51820
          AllowedIPs = 10.60.223.1/32
          PersistentKeepalive = 25" | sudo tee /etc/wireguard/wg0.conf

      - name: Connect to VPN
        run: |
          sudo wg-quick up wg0
          sleep 5  # Wait for connection

      - name: Pull latest code
        uses: appleboy/ssh-action@master
        with:
          host: 10.60.223.1
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/html
            git pull origin main
